### ISSUE TITLE
Unified and Plan B sdp output

### ISSUE THREAD

**Issue by jmartine** [otalk/sdp-jingle-json#19]
Since the release of Chrome Beta(67) I've experienced issues with multiple streams in the remote sdp.
It appears that the sdp being generated looks like a mix of unified and plan b.  It has both `a=msid:` and `a=ssrc:` lines.

Here is my `m=video` section of the sdp:
```
m=video 1 UDP/TLS/RTP/SAVPF 100 107 101 96 99 97
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:8vdtf1cd0ht95b
a=ice-pwd:50vc9kob902t2b71d6fpv563kd
a=fingerprint:sha-1 24:2C:1F:6E:E6:CB:B0:71:56:57:72:6F:89:E9:71:FA:DC:30:61:D3
a=setup:actpass
a=sendrecv
a=mid:video
a=msid:mixedmslabel mixedlabelvideo0
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=fmtp:100 x-google-start-bitrate=800
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:107 h264/90000
a=fmtp:107 x-google-start-bitrate=800
a=rtcp-fb:107 ccm fir
a=rtcp-fb:107 nack
a=rtcp-fb:107 nack pli
a=rtcp-fb:107 goog-remb
a=rtpmap:101 VP9/90000
a=fmtp:101 x-google-start-bitrate=800
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=107
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=ssrc-group:FID 3163310139 3882785586
a=ssrc:1178304027 cname:mixed
a=ssrc:1178304027 label:mixedlabelvideo0
a=ssrc:1178304027 msid:mixedmslabel mixedlabelvideo0
a=ssrc:1178304027 mslabel:mixedmslabel
a=ssrc:3163310139 cname:M6lRhvhFhZxyEREW
a=ssrc:3163310139 msid:03FRnIRhjov7MGc2LXxO3874SBPp5Qv2TZ6C df528499-22fa-4841-ad71-2fe83be5b3cd
a=ssrc:3882785586 cname:M6lRhvhFhZxyEREW
a=ssrc:3882785586 msid:03FRnIRhjov7MGc2LXxO3874SBPp5Qv2TZ6C df528499-22fa-4841-ad71-2fe83be5b3cd
```

If I remove the `a=msid:` from the sdp the stream gets added properly.  Has anyone else experienced this with the Beta or Dev versions of chrome?

Also I noticed the new repo rtcpeerconnection-jingle.  Does that mean this repo will not be maintained in the future.

**Comment by fippo** [comment]
I can reproduce that with a fiddle: https://jsfiddle.net/q39y5hqx/
triggers ontrack twice in M66 and only once in M67.
@taylor-b is this intended? (we are in non-spec land here so...)

> Also I noticed the new repo rtcpeerconnection-jingle. Does that mean this repo will not be maintained in the future.

It is not going to get much effort. We tried updating this repository to update the SDP module but this was more effort than it was worth.

**Comment by fippo** [comment]
tentative fix in #20

**Comment by alvestrand** [comment]
the double a=msid / a=ssrc: <number> msid was introduced in an attempt to get something that both Plan B and Unified Plan would be able to parse correctly for the single-stream case. In a reply and subsequent offers, we're supposed to do whatever the other guy did.

For multi-stream, this workaround isn't going to work.

**Comment by fippo** [comment]
@alvestrand yeah but the current behaviour suggest it looks for a=msid first and then ignores the multiple a=ssrc: msid. Checking if there are multiple a=ssrc lines first might be more robust, at least for a transition period :-)

Either way, fixed here pending review and new version.

**Comment by alvestrand** [comment]
I think you're looking for https://webrtc-review.googlesource.com/c/src/+/68764 to fix this.

**Comment by fippo** [comment]
that is pretty close in intent. Might be worth extending this to "you have a=msid and multiple a=ssrc: msid" :+1:

**Comment by alvestrand** [comment]
Hm. Anyone generating "a=msid mixedmslabel mixedmslabelvideo0" is doing SDP mangling, since native WebRTC generates these as random numbers.

Who's generating this SDP?

**Comment by fippo** [comment]
this package. The mixedmslabel stuff is a workaround for https://bugs.chromium.org/p/webrtc/issues/detail?id=1772 -- anything chrome does not recognize gets thrown into a stream you don't display, eliminating flickering in user-visible streams. Old hacks...

**Comment by taylor-b** [comment]
> I can reproduce that with a fiddle: https://jsfiddle.net/q39y5hqx/
> triggers ontrack twice in M66 and only once in M67.
> @taylor-b is this intended? (we are in non-spec land here so...)

In M67, I believe "a=msid" started taking precedence over "a=ssrc:X msid:". Looks like it happened in [this CL](https://webrtc-review.googlesource.com/c/src/+/61341). I forget the reasoning behind this, but we assumed it wouldn't make a difference because "you shouldn't be using a=msid if you have two tracks in one m= section".
